# Generated by Django 4.2.9 on 2024-02-05 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_product_saleproduct_sale_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='amount',
        ),
    ]
