# Generated by Django 4.2.9 on 2024-02-06 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_sale_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='user',
        ),
    ]
