# Generated by Django 4.2.9 on 2024-02-12 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='regarding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_tasks', to='tasks.task'),
        ),
    ]
