# Generated by Django 4.2.9 on 2024-02-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_regarding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Pending Customer', 'Pending Customer'), ('Pending Partner', 'Pending Partner'), ('Escalated', 'Escalated'), ('Completed', 'Completed')], default='New', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Pending Customer', 'Pending Customer'), ('Pending Partner', 'Pending Partner'), ('Escalated', 'Escalated'), ('Completed', 'Completed')], default='New', max_length=50),
        ),
    ]
