# Generated by Django 4.2.9 on 2024-02-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_sale_last_updated_by_alter_task_last_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('High Priority', 'High Priority'), ('Medium-High Priority', 'Medium-High Priority'), ('Medium-Low Priority', 'Medium-Low Priority'), ('Low Priority', 'Low Priority')], default='Low Priority', max_length=20),
        ),
    ]
