# Generated by Django 4.2.9 on 2024-02-21 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='company',
        ),
    ]
