# Generated by Django 4.2.9 on 2024-02-21 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_remove_task_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='individual',
            new_name='contact',
        ),
    ]
