# Generated by Django 4.2.9 on 2024-02-29 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_rename_individual_task_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_references', to='tasks.individual'),
        ),
    ]
